										   USE [master]
GO
/****** Object:  Database [Chengli]    Script Date: 12/07/2014 23:02:57 ******/
CREATE DATABASE [Chengli] ON  PRIMARY 
( NAME = N'chengli', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\chengli.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'chengli_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\chengli_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Chengli] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Chengli].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Chengli] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Chengli] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Chengli] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Chengli] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Chengli] SET ARITHABORT OFF
GO
ALTER DATABASE [Chengli] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Chengli] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Chengli] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Chengli] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Chengli] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Chengli] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Chengli] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Chengli] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Chengli] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Chengli] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Chengli] SET  DISABLE_BROKER
GO
ALTER DATABASE [Chengli] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Chengli] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Chengli] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Chengli] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Chengli] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Chengli] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Chengli] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Chengli] SET  READ_WRITE
GO
ALTER DATABASE [Chengli] SET RECOVERY FULL
GO
ALTER DATABASE [Chengli] SET  MULTI_USER
GO
ALTER DATABASE [Chengli] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Chengli] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'Chengli', N'ON'
GO
USE [Chengli]
GO
/****** Object:  Table [dbo].[ProductType]    Script Date: 12/07/2014 23:02:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TypeName] [nvarchar](20) NULL,
	[SmallType] [nvarchar](10) NULL,
 CONSTRAINT [PK_ProductType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 12/07/2014 23:02:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](100) NULL,
	[CreateTime] [datetime] NULL,
	[TypeId] [int] NULL,
	[ClickCount] [int] NULL,
	[MConent] [text] NULL,
	[SmallType] [nvarchar](10) NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Comment]    Script Date: 12/07/2014 23:02:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comment](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CreateTime] [datetime] NULL,
	[CreateUser] [nvarchar](50) NULL,
	[ComContent] [text] NULL,
 CONSTRAINT [PK_Comment] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
